import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { IoMenu } from 'react-icons/io5'
import {
  MdOutlinePendingActions,
  MdAccountTree,
  MdBugReport,
} from 'react-icons/md'
import { Providers } from './providers'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Quadro Kanban',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <div className="flex h-fit min-w-full flex-row justify-between bg-[#323232] bg-cover bg-fixed bg-no-repeat">
            <div className="flex flex-row items-center gap-6 py-4 pl-10 text-xl text-white">
              <IoMenu size={36} color="#FFFFFF" />
              <p className="font-medium">Tasks</p>
            </div>
            <div className="flex flex-row items-center gap-6 pr-10">
              <MdOutlinePendingActions size={36} color="#FFFFFF" />
              <MdAccountTree size={36} color="#FFFFFF" />
              <MdBugReport size={36} color="#FFFFFF" />
            </div>
          </div>
          {children}
        </Providers>
      </body>
    </html>
  )
}
